kind: pipeline
type: docker
name: alipay-sdk

steps:
  - name: build
    image: plugins/docker
    
    settings:
      debug: true
      repo: $${DOCKER_USERNAME}/alipay-sdk
      auto_tag: true
      environment:
        DOCKER_USERNAME:
          from_secret: docker_username
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      commands:
        - env
