kind: pipeline
type: docker
name: alipay-sdk

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: cynosure/alipay-sdk
      tag: ${DRONE_TAG=latest}
      insecure: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - tag